### ISSUE TITLE
error in build

### ISSUE THREAD

**Issue by Learner00100** [dishapatel010/Thunder#3]
how to solve this error??
![image](https://user-images.githubusercontent.com/102498820/211163651-079bfe6f-d206-4cf3-95d4-0746e057d396.png)
![image](https://user-images.githubusercontent.com/102498820/211163678-16b3a37c-71b7-4dd7-81f3-994afd1ae23f.png)
![image](https://user-images.githubusercontent.com/102498820/211163698-95f7ef43-4b58-49eb-ab34-36d5c9a09122.png)
![image](https://user-images.githubusercontent.com/102498820/211163718-3590c1ce-0825-448f-82a3-4d1426ede17f.png)

**Comment by dishapatel010** [comment]
Fork & fill constants
